name: CI CD

on:
  push:
    branches: [main]

jobs:
  infra:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: "set up google cloud sdk"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: "create gcs bucket for twilio function code"
        continue-on-error: true
        run: "gcloud storage buckets create gs://cf-imessage-code"

  build:
    runs-on: ubuntu-latest
    needs: infra

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: "upload twilio directory as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: code-directory-twilio
          path: twilio


      - name: "upload twilio artifact to google cloud storage"
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "twilio"
          destination: "cf-imessage-code"
          gzip: true

  deploy-twilio:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: "set up google cloud sdk"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: "copy source code directory"
        run: "gsutil cp -r gs://cf-imessage-code/twilio ."

      - name: "list files"
        run: "cd twilio; ls"

      - name: "zip source code files"
        run: "cd twilio; ls; zip twilio.zip *"

      - name: "upload source code"
        run: "gsutil cp twilio/twilio.zip gs://cf-imessage-code"

      - name: "deploy cloud function using gcloud"
        run:
          "gcloud  functions deploy twilio-endpoint --region=us-central1 \
          --runtime=python39 --gen2 --entry-point=main \
          --trigger-http \
          --allow-unauthenticated \
          --min-instances=1 \
          --memory=1Gi \
          --source=gs://cf-imessage-code/twilio.zip \
          --set-env-vars URL=${{secrets.URL}} \ 
          --set-env-vars SENDER=${{secrets.SENDER}}"