name: CI CD

on:
  push:
    branches: [main]

jobs:
  infra:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: "set up google cloud sdk"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: "create gcs bucket for twilio function code"
        continue-on-error: true
        run: "gcloud storage buckets create gs://${{vars.TWILIO_SOURCE_GCS}}"

  build:
    runs-on: ubuntu-latest
    needs: infra

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: "upload twilio directory as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: code-directory-twilio
          path: twilio


      - name: "upload twilio artifact to google cloud storage"
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "twilio"
          destination: ${{vars.TWILIO_SOURCE_GCS}}
          gzip: true

  deploy-twilio:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: "set up google cloud sdk"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: "copy source code directory"
        run: "gsutil cp -r gs://${{vars.TWILIO_SOURCE_GCS}}/twilio ."

      - name: "list files"
        run: "cd twilio; ls"

      - name: "zip source code files"
        run: "cd twilio; ls; zip twilio.zip *"

      - name: "upload source code"
        run: "gsutil cp twilio/twilio.zip gs://${{vars.TWILIO_SOURCE_GCS}}"

      - name: "deploy cloud function using gcloud"
        run:
          "gcloud  functions deploy twilio-endpoint --region=${{vars.LOCATION}} \
          --runtime=python39 --gen2 --entry-point=main \
          --trigger-http \
          --allow-unauthenticated \
          --min-instances=1 \
          --memory=1Gi \
          --source=gs://${{vars.TWILIO_SOURCE_GCS}}/twilio.zip \
